"""current balance

Revision ID: 61ac3287637e
Revises: 80c9773afb2f
Create Date: 2021-04-11 11:20:19.334241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ac3287637e'
down_revision = '80c9773afb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_balance')
    # ### end Alembic commands ###
